// PluginComDll.idl : PluginComDll 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(PluginComDll.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C38672FA-B5C8-4D9D-89B5-2D71F0760661),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ITextFile : IDispatch{
};

[
	object,
	uuid(E46E1B5B-2891-414F-A21A-17B00231E650),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISysInfo : IDispatch{
};

[
	uuid(A22E18F1-95F8-4FDB-99D2-188E5FB12B23),
	version(1.0),
]
library PluginComDllLib
{
	importlib("stdole2.tlb");

	[
		uuid(40756D41-E6C7-4648-80C4-AB70A325F831)		
	]
	dispinterface _ITextFileEvents
	{
		properties:
		methods:
	};

	[
		uuid(40613676-C8A5-4879-A59B-9CE6406476F6)		
	]
	coclass TextFile
	{
		[default] interface ITextFile;
		[default, source] dispinterface _ITextFileEvents;
	};

	[
		uuid(FAC6FC19-9B22-4904-A656-581FCB35EC98)		
	]
	dispinterface _ISysInfoEvents
	{
		properties:
		methods:
	};

	[
		uuid(6D7595BD-BFB0-4D2C-906B-247028691A50)		
	]
	coclass SysInfo
	{
		[default] interface ISysInfo;
		[default, source] dispinterface _ISysInfoEvents;
	};
};

